import type { Metadata } from 'next';
import { Prompt } from 'next/font/google';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { ThemeProvider } from '@/context/ThemeContext';
import Navbar from '@/components/Navbar';
import { AuthProvider } from '@/context/AuthContext';
import ChatbotButton from '@/components/ChatbotButton';
import { icon } from '@fortawesome/fontawesome-svg-core';

const prompt = Prompt({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Limbic',
  description: 'Generated by create next app',
  icons: { icon: '/limbic-logo.webp' },
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang="en">
      <body className={`${prompt.className} flex min-h-screen`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            {/* <AuthProvider> */}
            <Navbar />
            <div className="w-full pt-12 md:p-0">
              {children}
              <div className="fixed bottom-8 right-8">
                <ChatbotButton />
              </div>
            </div>
            {/* </AuthProvider> */}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
